# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group minor and patch updates
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "*eslint*"
          - "*prettier*"
          - "@typescript-eslint/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*eslint*"
          - "*prettier*"
          - "@typescript-eslint/*"
          - "typescript"
        update-types:
          - "patch"
    # Reviewers for dependency updates
    reviewers:
      - "aman-dhakar-191"
    # Add commit message prefix
    commit-message:
      prefix: "deps"
      include: "scope"
    # Rebase strategy
    rebase-strategy: "auto"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"